FROM golang:1.25 AS compile
ARG NODE_VERSION=22.22.3
RUN curl -fsSL https://deb.nodesource.com/setup_$(echo $NODE_VERSION | cut -d. -f1).x | bash - \
    && apt-get install -yq nodejs build-essential \
    && corepack enable \
    && corepack prepare pnpm@11 --activate
WORKDIR /build
COPY . .
RUN make build

FROM quay.io/prometheus/busybox-linux-amd64:latest
COPY --from=compile /build/prometheus        /bin/prometheus
COPY --from=compile /build/promtool          /bin/promtool
COPY --from=compile /build/documentation/examples/prometheus.yml /etc/prometheus/prometheus.yml
WORKDIR /prometheus
RUN chown -R nobody:nobody /etc/prometheus /prometheus
USER       nobody
EXPOSE     9090
VOLUME     [ "/prometheus" ]
ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus" ]
